environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn install

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

branches:
  only:
  - master
  - /v[0-9]+(\.[0-9]+)*/

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run tests
  - yarn run test:cov
  - yarn lint

# Don't actually build.
build: off
shallow_clone: true
